name: Devsecops cicd pipeline
on:
  push:
    branches:
      - qa
    paths:
      - client/**
      - server/**
      - .github/workflow/qa.yml

jobs:
  gitleaks-scan:
    name: Gitleack Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v7
        with:
          ref: qa

      - name: Run Gitleaks Scan
        run: |
          docker run --rm \
          -v "${{ github.workspace }}:/repo" \
          zricethezav/gitleaks:latest detect \
          --source=/repo \
          --report-format=json \
          --report-path=/repo/gitleaks-report.json \
          --redact \
          --exit-code 0
      - name: Upload Gitleaks report
        uses: actions/upload-artifact@v7
        with:
          name: gitleaks-report
          path: gitleaks-report.json
          if-no-files-found: warn
    
  
  
