name: Devsecops cicd pipeline
on:
  push:
    branches:
      - qa
    paths:
      - client/**
      - server/**
      - .github/workflows/qa.yml

jobs:
  gitleaks-scan:
    name: Gitleack Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v7
        with:
          ref: qa

      - name: Run Gitleaks Scan
        run: |
          docker run --rm \
          -v "${{ github.workspace }}:/repo" \
          zricethezav/gitleaks:latest detect \
          --source=/repo \
          --report-format=json \
          --report-path=/repo/gitleaks-report.json \
          --redact \
          --exit-code 0
      - name: Upload Gitleaks report
        uses: actions/upload-artifact@v7
        with:
          name: gitleaks-report
          path: gitleaks-report.json
          if-no-files-found: warn
      
  checkov-terraform:
    name: Checkov Terraform Scan
    runs-on: ubuntu-latest
    needs: gitleaks-scan
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v7
        with:
          ref: qa

      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.13'
      - name: Install Checkov
        run: pip install Checkov
      - name: Run Terraform Scan
        run: |
          checkov -d . \
            --framework terraform \
            --output json > checkov-terraform-report.json || true
      - name: Upload Checkov Terraform Report
        uses: actions/upload-artifact@v7
        with:
          name: checkov-terraform-report
          path: checkov-terraform-report.json
          if-no-files-found: warn

  checkov-k8s:
    name: Checkov Kuberneties Scan
    runs-on: ubuntu-latest
    needs: gitleaks-scan
    steps:
      - name: Checkout source code
        uses: actions/checkout@v7
        with:
          ref: qa
      - name: Setup python 
        uses: actions/setup-python@v7
        with:
          python-version: '3.13' 
      - name: Checkov Install
        run: pip install checkov
      - name: start the scan
        run: |
          checkov -d . \
            --framework kubernities \
            --output json > checkov-k8-report.json || true
      - name: Artifact save
        uses: actions/upload-artifact@v7
        with: 
          name: checkov-k8-report
          path: checkov-k8-report.json
          if-no-files-found: warn

  checkov-dockerfile:
    name: Checkov Dockerfile Scan
    runs-on: ubuntu-latest
    needs: gitleaks-scan
    steps:
      - name: Checkout source code
        uses: actions/checkout@v7
        with:
          ref: qa
      - name: Setup python 
        uses: actions/setup-python@v7
        with:
          python-version: '3.13' 
      - name: Checkov Install
        run: pip install checkov
      - name: start the scan
        run: |
          checkov -d . \
            --framework dockerfile \
            --output json > checkov-dockerfile-report.json || true
      - name: Artifact save
        uses: actions/upload-artifact@v7
        with: 
          name: checkov-dockerfile-report
          path: checkov-dockerfile-report.json
          if-no-files-found: warn

  client-trivy-fs:
    name: Client Trivy FS Scan
    runs-on: ubuntu-latest
    needs: gitleaks-scan
    steps:
      - name: Checkout source code
        uses: actions/checkout@v7
        with:
          ref: qa
      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.6
        with:
          cache: true
      - name: Verify Trivy Installation
        run: |
          trivy --version 
          which trivy

      - name: Run Trivy FS Scan on Client (JSON)
        run: |
          trivy fs ./client \
            --format json \
            --output client-trivy-fs-report.json \
            --severity HIGH_CRITICAL \
            --ignore-unfixed \
            --exit-code 0

      - name: Run Trivy FS scan on Client (TABLE)
        run: |
          trivy fs ./client \
            --format table \
            --severity HIGH_CRITICAL \
            --ignore-unfixed \
            --exit-code 0 > client-trivy-fs-report.txt
      - name: Upload Client Trivy Json report
        uses: actions/upload-artifact@v7
        with: 
          name: client-trivy-fs-Json-report
          path: client-trivy-fs-report.json
          if-no-files-found: warn
      - name: Upload Server Trivy table report
        uses: actions/upload-artifact@v7
        with: 
          name: client-trivy-fs-table-report
          path: client-trivy-fs-report.txt
          if-no-files-found: warn

  server-trivy-fs:
    name: Server Trivy FS Scan
    runs-on: ubuntu-latest
    needs: gitleaks-scan
    steps:
      - name: code checkout
        uses: actions/checkout@v7
        with:
          ref: qa
      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.6
        with:
          version: v0.68.2
          cache: true
      - name: Verify the Trivy Installation
        run: |
          trivy --version
          which trivy

      - name: Run trivy fs scan on server (Json)
        run: |
          trivy fs ./server \
            --format json \
            --output server-trivy-fs-report.json \
            --severity HIGH_CRITICAL \
            --ignore-unfixed \
            --exit-code 0

      - name: Run trivy fs scan on server (table)
        run: |
           trivy fs ./server \
             --format table \
             --severity HIGH_CRITICAL \
             --ignore-unfixed \
             --exit-code 0 > server-trivy-fs-report.txt
      - name: Upload Server Trivy Json report
        uses: actions/upload-artifact@v7
        with: 
          name: server-trivy-fs-json-report
          path: server-trivy-fs-report.json
          if-no-files-found: warn
          
      - name: Upload Server Trivy table report
        uses: actions/upload-artifact@v7
        with: 
          name: server-trivy-fs-table-report
          path: server-trivy-fs-report.txt
          if-no-files-found: warn        
          

























        
          
      
  
